# Generated by Django 2.0.4 on 2018-04-28 18:45

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
