# Generated by Django 2.0.4 on 2018-04-28 21:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hero',
            field=wagtail.core.fields.StreamField((('hero', wagtail.core.blocks.StructBlock((('subject', wagtail.core.blocks.CharBlock(required=False)),))),), default=''),
            preserve_default=False,
        ),
    ]
