# Generated by Django 2.0.4 on 2018-04-28 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_hero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='author',
            new_name='keynotes',
        ),
    ]
