# Generated by Django 2.0 on 2018-08-29 18:44

from django.db import migrations
import home.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180822_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=wagtail.core.fields.StreamField((('row_block', wagtail.core.blocks.StreamBlock((('paragraph_block', home.blocks.ParagraphBlock()), ('image_block', home.blocks.ImageBlock()), ('pull_quote_block', home.blocks.PullQuoteBlock())), max_num=2, min_num=1)),), blank=True),
        ),
    ]
