# Generated by Django 2.0 on 2018-09-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20180830_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='body',
        ),
    ]
