# Generated by Django 2.0 on 2018-09-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_featured_talks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='featured_talks',
            field=models.ManyToManyField(null=True, to='talks.Talk'),
        ),
    ]
