# Generated by Django 2.0 on 2018-09-17 17:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0012_talk_description'),
        ('events', '0016_auto_20180917_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeaturedTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='featured_talks',
        ),
        migrations.AddField(
            model_name='eventfeaturedtalk',
            name='event',
            field=modelcluster.fields.ParentalManyToManyField(related_name='event_talks', to='events.Event'),
        ),
        migrations.AddField(
            model_name='eventfeaturedtalk',
            name='talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='talks.Talk'),
        ),
    ]
