# Generated by Django 2.0 on 2018-09-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20180917_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_image',
            new_name='featured_image',
        ),
    ]
