# Generated by Django 2.0 on 2018-10-17 15:00

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20180928_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlist',
            name='copy',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Summary to display at top of list page', null=True),
        ),
    ]
