# Generated by Django 2.0 on 2018-10-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_eventlist_copy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='exerpt',
            new_name='summary',
        ),
    ]
