# Generated by Django 2.0 on 2018-11-05 20:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20181018_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('summary', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_presentations', to='events.Event')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='eventfeaturedtalk',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventfeaturedtalk',
            name='talk',
        ),
        migrations.DeleteModel(
            name='EventFeaturedTalk',
        ),
    ]
