# Generated by Django 2.0 on 2018-11-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20181018_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.CharField(help_text='Summary for list view, not displayed in detail view', max_length=600),
        ),
    ]
