# Generated by Django 2.0 on 2018-08-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('projects', '0002_projectpage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='graphic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
