# Generated by Django 2.0 on 2018-08-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectpage_graphic'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
