# Generated by Django 2.0 on 2018-08-29 18:44

from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('projects', '0004_projectpage_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='exerpt',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='excerpt',
            field=wagtail.core.fields.RichTextField(help_text='Summary for list view, not displayed in detail view', null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='excerpt_graphic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='excerpt_header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='summary',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='body',
            field=wagtail.core.fields.StreamField((('row_block', wagtail.core.blocks.StreamBlock((('paragraph_block', home.blocks.ParagraphBlock()), ('image_block', home.blocks.ImageBlock()), ('pull_quote_block', home.blocks.PullQuoteBlock())), max_num=2, min_num=1)),), blank=True),
        ),
    ]
