# Generated by Django 2.0 on 2018-09-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180830_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='graphic',
            new_name='featured_image',
        ),
    ]
