# Generated by Django 2.0 on 2018-09-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180904_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='excerpt_graphic',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='excerpt_header',
        ),
    ]
