# Generated by Django 2.0 on 2018-10-18 16:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='copy',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Summary to display at top of list page', null=True),
        ),
    ]
