# Generated by Django 2.0 on 2018-11-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectlist_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='summary',
            field=models.CharField(max_length=600),
        ),
    ]
