image: docker:latest

variables:
   DOCKER_HOST: tcp://docker:2375/
   DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  
build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/excellalabs/labs-website-wagtail .
    - docker login registry.gitlab.com
    - docker push registry.gitlab.com/excellalabs/labs-website-wagtail

test:
  stage: test
  script:
    - docker exec registry.gitlab.com/excellalabs/labs-website-wagtail python manage.py test

deploy:
  stage: deploy
  script:
    - echo "deploy stage"