variables:
   DOCKER_HOST: tcp://docker:2375/
   DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  image: docker:latest

  stage: build
  script:
    - echo "build"
    #- docker build -t registry.gitlab.com/excellalabs/labs-website-wagtail:latest .
    #- docker push registry.gitlab.com/excellalabs/labs-website-wagtail:latest

test:
  image: docker:latest

  stage: test
  script:
    - echo "test"
    #- docker pull registry.gitlab.com/excellalabs/labs-website-wagtail:latest
    #- docker images
    #- docker run registry.gitlab.com/excellalabs/labs-website-wagtail:latest python manage.py test

deploy:
  image: docker:latest
  stage: deploy
  script:
  script:
    - curl -L -o /usr/bin/kubectl "https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/bin/linux/amd64/kubectl"
    - chmod +x /usr/bin/kubectl
    - kubectl version --client

    - kubectl config set-cluster eks-gitlab-test server=$K8S_URL
    - kubectl run deploy --image=registry.gitlab.com/excellalabs/labs-website-wagtail:latest --port=8000
