# Generated by Django 2.0.5 on 2018-05-11 14:09

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_showcaselist'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasepage',
            name='exerpt',
            field=wagtail.core.fields.RichTextField(default='', help_text='Summary for list view, not displayed in detail view'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showcasepage',
            name='body',
            field=wagtail.core.fields.StreamField((('body', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()))),
        ),
    ]
