# Generated by Django 2.0 on 2018-06-07 21:08

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_auto_20180511_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasepage',
            name='intro_video',
            field=wagtail.core.fields.StreamField((('iframe', wagtail.core.blocks.StructBlock((('source', wagtail.core.blocks.URLBlock()), ('height', wagtail.core.blocks.IntegerBlock(min_value=0)), ('width', wagtail.core.blocks.IntegerBlock(min_value=0)), ('extra_attributes', wagtail.core.blocks.CharBlock(required=False))))),), blank=True),
        ),
        migrations.AlterField(
            model_name='showcasepage',
            name='hero',
            field=wagtail.core.fields.StreamField((('hero', wagtail.core.blocks.StructBlock((('subject', wagtail.core.blocks.CharBlock(required=False)), ('alternate_title', wagtail.core.blocks.CharBlock(required=False))))),)),
        ),
    ]
