# Generated by Django 2.0 on 2018-08-16 16:01

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_auto_20180613_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcasepage',
            name='banner',
        ),
        migrations.AddField(
            model_name='showcasepage',
            name='alternate_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='showcasepage',
            name='subject',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='showcasepage',
            name='body',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()))),
        ),
    ]
