# Generated by Django 2.0.4 on 2018-04-28 16:22

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_us',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
