# Generated by Django 2.0.4 on 2018-04-28 17:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero',
            field=wagtail.core.fields.StreamField((('hero', wagtail.core.blocks.StructBlock((('subject', wagtail.core.blocks.CharBlock(required=False)), ('byline', wagtail.core.blocks.CharBlock(required=False))))),), default=''),
            preserve_default=False,
        ),
    ]
