# Generated by Django 2.0.4 on 2018-04-28 17:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero',
            field=wagtail.core.fields.StreamField((('hero', wagtail.core.blocks.StructBlock((('subject', wagtail.core.blocks.CharBlock(required=False)),))),)),
        ),
    ]
