# Generated by Django 2.0.4 on 2018-04-28 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('talks', '0002_auto_20180428_1828'),
        ('home', '0005_auto_20180428_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='event_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.Event'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='talk_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='talks.Talk'),
        ),
    ]
