# Generated by Django 2.0.4 on 2018-04-28 18:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180428_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_us',
            field=wagtail.core.fields.StreamField((('about_us', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock(blank=True))))),)),
        ),
    ]
