# Generated by Django 2.0.4 on 2018-05-02 13:27

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180428_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='event_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='talk_page',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured',
            field=wagtail.core.fields.StreamField((('event', wagtail.core.blocks.PageChooserBlock(target_model=['events.Event'])), ('talk', wagtail.core.blocks.PageChooserBlock(target_model=['talks.Talk'])), ('showcase', wagtail.core.blocks.PageChooserBlock(target_model=['showcase.ShowcasePage']))), default=''),
            preserve_default=False,
        ),
    ]
