# Generated by Django 2.0.4 on 2018-05-04 13:47

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180502_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='featured',
            field=wagtail.core.fields.StreamField((('event_featured', wagtail.core.blocks.PageChooserBlock(target_model=['events.Event'])), ('event', wagtail.core.blocks.PageChooserBlock(target_model=['events.Event'])), ('talk', wagtail.core.blocks.PageChooserBlock(target_model=['talks.Talk'])), ('showcase', wagtail.core.blocks.PageChooserBlock(target_model=['showcase.ShowcasePage'])))),
        ),
    ]
