# Generated by Django 2.0.5 on 2018-05-11 12:12

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_navlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navlinks',
            name='pages',
            field=wagtail.core.fields.StreamField((('pages', wagtail.core.blocks.PageChooserBlock()), ('icons', wagtail.core.blocks.StructBlock((('icon', wagtail.core.blocks.CharBlock(help_text='Font Awesome icon name')), ('url', wagtail.core.blocks.URLBlock(help_text='URL to link to'))))))),
        ),
    ]
