# Generated by Django 2.0.5 on 2018-05-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180511_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navlinks',
            old_name='pages',
            new_name='links',
        ),
    ]
