# Generated by Django 2.0 on 2018-08-16 19:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180816_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='featured',
            field=wagtail.core.fields.StreamField((('event_featured', wagtail.core.blocks.PageChooserBlock(target_model=['events.Event'])), ('talk_featured', wagtail.core.blocks.PageChooserBlock(target_model=['talks.Talk'])), ('project_featured', wagtail.core.blocks.PageChooserBlock(target_model=['projects.ProjectPage'])), ('event', wagtail.core.blocks.PageChooserBlock(target_model=['events.Event'])), ('talk', wagtail.core.blocks.PageChooserBlock(target_model=['talks.Talk'])), ('project', wagtail.core.blocks.PageChooserBlock(target_model=['projects.ProjectPage'])))),
        ),
    ]
