# Generated by Django 2.0 on 2018-09-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20180830_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='feed_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='number_of_posts',
        ),
    ]
