# Generated by Django 2.0 on 2018-08-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0006_auto_20180613_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='banner',
        ),
        migrations.AddField(
            model_name='talk',
            name='alternate_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='talk',
            name='subject',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
