# Generated by Django 2.0 on 2018-11-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0016_auto_20181023_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='summary',
            field=models.CharField(help_text='Summary for list view, not displayed in detail view', max_length=600),
        ),
    ]
